"""Create Tables

Revision ID: 38acabfba6e7
Revises: 51ee7e2c5d34
Create Date: 2024-06-20 12:52:08.485919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38acabfba6e7'
down_revision: Union[str, None] = '51ee7e2c5d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoriess',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productss',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productss')
    op.drop_table('categoriess')
    # ### end Alembic commands ###
