"""Add weight parametr to products table

Revision ID: 3cfbe48a6d56
Revises: 2848320187a5
Create Date: 2024-06-20 15:21:48.777253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfbe48a6d56'
down_revision: Union[str, None] = '2848320187a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('weight', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'weight')
    # ### end Alembic commands ###
